### ISSUE TITLE
Unsupported protocol on startup

### ISSUE THREAD

**Issue by DanoOM** [allegro/turnilo#385]
Hi all, I am a complete noob to node/npm.
On my centos 7 build, I have done the following:

curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
sudo yum install nodejs
node --version
v10.15.3

then:
npm -v
6.4.x <-- I have since updated..since this was not 6.5, per required on the readme.md

so..
sudo npm update npm -g
6.9.0   

ok well this isn't 6.5, but I have no idea how to 'install' this exact version (any help here would be appreciated)
so proceed to install..

```
sudo npm install -g turnilo
all seems good
[centos@uswest2-dev-turnilo-001 ~]$ turnilo --druid uswest2-dev-aldruidquery-001.aws-dev:8082
Starting Turnilo v1.14.0
Turnilo is listening on address :: port 9090
Adding cluster manager for 'druid' with 0 dataCubes
Fatal settings load error: Unsupported protocol: uswest2-dev-aldruidquery-001.aws-dev:
Error: Unsupported protocol: uswest2-dev-aldruidquery-001.aws-dev:
    at defaultPort (/usr/lib/node_modules/turnilo/build/server/utils/requester/requester.js:19:19)
    at getHostAndProtocol (/usr/lib/node_modules/turnilo/build/server/utils/requester/requester.js:27:41)
    at createDruidRequester (/usr/lib/node_modules/turnilo/build/server/utils/requester/requester.js:31:14)
    at Object.properRequesterFactory (/usr/lib/node_modules/turnilo/build/server/utils/requester/requester.js:46:45)
    at ClusterManager.updateRequester (/usr/lib/node_modules/turnilo/build/server/utils/cluster-manager/cluster-manager.js:151:38)
    at new ClusterManager (/usr/lib/node_modules/turnilo/build/server/utils/cluster-manager/cluster-manager.js:83:14)
    at SettingsManager.addClusterManager (/usr/lib/node_modules/turnilo/build/server/utils/settings-manager/settings-manager.js:86:30)
    at /usr/lib/node_modules/turnilo/build/server/utils/settings-manager/settings-manager.js:143:68
    at Array.map (<anonymous>)
    at SettingsManager.reviseClusters (/usr/lib/node_modules/turnilo/build/server/utils/settings-manager/settings-manager.js:143:30)
(node:32426) UnhandledPromiseRejectionWarning: Error: Unsupported protocol: uswest2-dev-aldruidquery-001.aws-dev:
    at defaultPort (/usr/lib/node_modules/turnilo/build/server/utils/requester/requester.js:19:19)
    at getHostAndProtocol (/usr/lib/node_modules/turnilo/build/server/utils/requester/requester.js:27:41)
    at createDruidRequester (/usr/lib/node_modules/turnilo/build/server/utils/requester/requester.js:31:14)
    at Object.properRequesterFactory (/usr/lib/node_modules/turnilo/build/server/utils/requester/requester.js:46:45)
    at ClusterManager.updateRequester (/usr/lib/node_modules/turnilo/build/server/utils/cluster-manager/cluster-manager.js:151:38)
    at new ClusterManager (/usr/lib/node_modules/turnilo/build/server/utils/cluster-manager/cluster-manager.js:83:14)
    at SettingsManager.addClusterManager (/usr/lib/node_modules/turnilo/build/server/utils/settings-manager/settings-manager.js:86:30)
    at /usr/lib/node_modules/turnilo/build/server/utils/settings-manager/settings-manager.js:143:68
    at Array.map (<anonymous>)
    at SettingsManager.reviseClusters (/usr/lib/node_modules/turnilo/build/server/utils/settings-manager/settings-manager.js:143:30)
(node:32426) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32426) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by l2dy** [comment]
Can you try `turnilo --druid http://uswest2-dev-aldruidquery-001.aws-dev:8082`?

**Comment by DanoOM** [comment]
wow.that is somewhat embarrassing..I actually removed http:// when 'copied' my link.since the docs:
show: broker_host:broker_port
might want to update, the readme to say:
turnilo --druid <BrokerUrlAndport> 
or some such :)
Thanks for the tip :)

**Comment by DanoOM** [comment]
hrm, ok..well turnilo startup now, and I see stdio, showing 'Got the latest time for ...
When I browse to host:9090, I get a blank page :(
well It flashes an 'orange' gridge of dots in the center of the page, then it goes blank.
Looking at the network transfer, I see:
'Main' page return 200, then 3 other calls, all returning 200:
main.js?v=1.14.0
app.7e094f...js
favicon.ico..

**Comment by adrianmroz** [comment]
Yeah, we should update docs (I only updated configuration docs when changed that) and handle better incorrect input.

Is your druid instance available publicly? If not I can just guess that introspection didn't return any measures inside DataCube (I'm guessing it found only one DataCube and redirected to CubeView), so Resolutions couldn't find nothing to show. 

Turnilo without configuration file is an uncharted territory for me, I'm not sure on what level such cases are handled.

**Comment by adrianmroz** [comment]
Update docs on protocols.
