### ISSUE TITLE
Cluster.url url_1.URL is not a function

### ISSUE THREAD

**Issue by satybald** [allegro/turnilo#400]
While starting turnilo 1.14.0 version it throws an exception `Cluster.url url_1.URL is not a function`. Same happens while providing druid broker URL via a config file.

```
turnilo --druid my_druid_host:8080
Starting Turnilo v1.14.0
/usr/local/lib/node_modules/turnilo/node_modules/immutable-class/build/base-immutable/base-immutable.js:56
                        throw new Error(this.constructor.name + "." + propertyName + " " + e.message);
                        ^

Error: Cluster.url url_1.URL is not a function
    at Cluster.BaseImmutable (/usr/local/lib/node_modules/turnilo/node_modules/immutable-class/build/base-immutable/base-immutable.js:56:31)
    at new Cluster (/usr/local/lib/node_modules/turnilo/build/common/models/cluster/cluster.js:41:47)
    at Object.<anonymous> (/usr/local/lib/node_modules/turnilo/build/server/config.js:190:54)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/turnilo/build/server/app.js:8:16)
```

**Comment by adrianmroz** [comment]
What node version do you have? WHATWG `url` is implemented in node since 6.13.0.

**Comment by satybald** [comment]
I'm using an old nodejs version that I've installed via apt-get in ubuntu.

```
node --version
v4.2.6
```

**Comment by satybald** [comment]
what's the recommended version of nodejs to run?

**Comment by l2dy** [comment]
> what's the recommended version of nodejs to run?

In the README:
* Node.js - 10.x or 8.x version.
* npm - 6.5.0 version.

**Comment by satybald** [comment]
thanks for the information!
