### ISSUE TITLE
 TypeScript emitted no output for 

### ISSUE THREAD

**Issue by Fisher4U** [allegro/turnilo#645]
[./src/client/main.tsx] 544 bytes {main} [built] [failed] [1 error]

ERROR in ./src/client/main.tsx
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for /Users/jiapingzhang/open-projects/turnilo-pivot/src/client/main.tsx.
    at makeSourceMapAndFinish (/Users/jiapingzhang/open-projects/turnilo-pivot/node_modules/ts-loader/dist/index.js:80:15)
    at successLoader (/Users/jiapingzhang/open-projects/turnilo-pivot/node_modules/ts-loader/dist/index.js:68:9)
    at Object.loader (/Users/jiapingzhang/open-projects/turnilo-pivot/node_modules/ts-loader/dist/index.js:22:12)
 @ multi webpack-hot-middleware/client ./src/client/main.tsx main[1]
ℹ ｢wdm｣: Failed to compile.
Loaded file /Users/jiapingzhang/open-projects/turnilo-pivot/assets/data/wikiticker-2015-09-12-sampled.json (rows = 39244)
Got native dataset update for wiki

**Comment by adrianmroz** [comment]
We need more information. What version, what environment? What command you try to execute and what you're trying to do?

**Comment by adrianmroz** [comment]
Please reopen if you have any new information.
