### ISSUE TITLE
Display Druid query

### ISSUE THREAD

**Issue by mkuthan** [allegro/turnilo#68]
For debug purposes it would be nice to display Druid query (queries) used for generating current Turnilo view. Right now, the queries are shown only on console in verbose mode.

TODO: Define UI.

**Comment by trtg** [comment]
This feature appears broken using the wikipedia example data:

```
Client Error: {"message":"Uncaught Error: must filter on time unless the allowEternity flag is set","file":"http://10.101.1.42:9090/main.js?v=1.9.1","line":40,"column":48239,"stack":"Error: must filter on time unless the allowEternity flag is set\n    at e.timeFilterToIntervals (http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:275268)\n    at e.filterToDruid (http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:275013)\n    at n.getQueryAndPostTransform (http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:313239)\n    at n.e.simulateValue (http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:257596)\n    at http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:151848\n    at n.fillDatasetExternalAlterations (http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:115504)\n    at n.fillExpressionExternalAlteration (http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:115208)\n    at http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:151811\n    at n.e._computeResolvedSimulate (http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:152023)\n    at n.e.simulateQueryPlan (http://10.101.1.42:9090/app.2a1cfd0a76fdf9135523.js:1:151495)"},"sometimeLater":"2016-09-12T06:48:00Z","channel":"vi","cityName":null,"comment":"fix using [[Project:AWB|AWB]]","commentLength":29,"countryI
```
