### ISSUE TITLE
error: unsupported aggregate action $__SEGMENT__:DATASET.collect($raw_creative_name:STRING) (as __VALUE__)

### ISSUE THREAD

**Issue by realkimmy** [allegro/turnilo#782]
```
- name: test
   title: Test
   formula: $main.filter($action_type=="AD").filter($spend>0).collect($raw_creative_name)
```

```
error: unsupported aggregate action $__SEGMENT__:DATASET.collect($raw_creative_name:STRING) (as __VALUE__)
Error: unsupported aggregate action $__SEGMENT__:DATASET.collect($raw_creative_name:STRING) (as __VALUE__)
    at DruidAggregationBuilder.expressionToAggregation (/Users/ying/workspace/code/topbi2/node_modules/@topgames/plywood/build/plywood.js:11538:19)
    at DruidAggregationBuilder.applyToAggregation (/Users/ying/workspace/code/topbi2/node_modules/@topgames/plywood/build/plywood.js:11497:14)
    at DruidAggregationBuilder.makeAggregationsAndPostAggregations (/Users/ying/workspace/code/topbi2/node_modules/@topgames/plywood/build/plywood.js:11484:18)
    at DruidExternal.getQueryAndPostTransform (/Users/ying/workspace/code/topbi2/node_modules/@topgames/plywood/build/plywood.js:13466:85)
    at DruidExternal.External.queryBasicValueStream (/Users/ying/workspace/code/topbi2/node_modules/@topgames/plywood/build/plywood.js:10172:42)
    at DruidExternal.queryBasicValueStream (/Users/ying/workspace/code/topbi2/node_modules/@topgames/plywood/build/plywood.js:13856:55)
    at DruidExternal.External.queryValueStream (/Users/ying/workspace/code/topbi2/node_modules/@topgames/plywood/build/plywood.js:10187:32)
    at DruidExternal.External.queryValue (/Users/ying/workspace/code/topbi2/node_modules/@topgames/plywood/build/plywood.js:10159:27)
    at /Users/ying/workspace/code/topbi2/node_modules/@topgames/plywood/build/plywood.js:4708:49
    at /Users/ying/workspace/code/topbi2/node_modules/@topgames/plywood/build/plywood.js:3434:20
```

**Comment by adrianmroz-allegro** [comment]
Doesn't look like plywood supports `CollectExpression` as aggregation: https://github.com/implydata/plywood/blob/master/src/external/utils/druidAggregationBuilder.ts#L202

More like issue to report on their repository: https://github.com/implydata/plywood/issues

Out of the curiosity, are you trying to define dimension with this expression? On one hand measure can't have value represented as set. On the other hand, I'm not sure if that's even possible as dimension. It's hard to imagine how it would be used by druid query planner.
