### ISSUE TITLE
Turnilo fails to discover datasources with variance aggregator included at indexing time

### ISSUE THREAD

**Issue by michalmisiewicz** [allegro/turnilo#95]
Turnilo fails to discover datasources that uses pre-aggregating variance at ingestion time from [druid-stats](http://druid.io/docs/latest/development/extensions-core/stats.html) extension

**Comment by kyleboyle** [comment]
Fatal settings load error: unsupported type NULL with nativeType variance
Error: unsupported type NULL with nativeType variance
    at _loop_1 (/Users/kyle/temp/turnilo/node_modules/turnilo/build/common/models/data-cube/data-cube.js:731:31)
    at DataCube.addAttributes (/Users/kyle/temp/turnilo/node_modules/turnilo/build/common/models/data-cube/data-cube.js:741:13)
    at DataCube.updateWithExternal (/Users/kyle/temp/turnilo/node_modules/turnilo/build/common/models/data-cube/data-cube.js:515:21)
    at Function.DataCube.fromClusterAndExternal (/Users/kyle/temp/turnilo/node_modules/turnilo/build/common/models/data-cube/data-cube.js:160:48)
    at SettingsManager.onExternalChange (/Users/kyle/temp/turnilo/node_modules/turnilo/build/server/utils/settings-manager/settings-manager.js:240:45)
    at ClusterManager.updateManagedExternal (/Users/kyle/temp/turnilo/node_modules/turnilo/build/server/utils/cluster-manager/cluster-manager.js:79:21)
    at /Users/kyle/temp/turnilo/node_modules/turnilo/build/server/utils/cluster-manager/cluster-manager.js:223:26
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
